export enum Events {
  PLAY = "PLAY",
  PAUSE = "PAUSE",
  LOOP_COMPLETED = "LOOP_COMPLETED",
  COMPLETE = "COMPLETE",
  LOADED = "LOADED",
}

export enum Interactions {
  PLAY = "PLAY",
  PLAY_REVERSE = "PLAY_REVERSE",
  PAUSE = "PAUSE",
  TOGGLE = "TOGGLE",
  RESET_ANIMATION = "RESET_ANIMATION",
}
